batchsize: 16
iteration: 450000
iteration_decay_start: 400000
seed: 0
display_interval: 100
progressbar_interval: 10
snapshot_interval: 10000
evaluation_interval: 1000

models:
  generator:
    fn: gen_models/resnet_small_scbn.py
    name: SCBNResNetGenerator
    args:
      dim_z: 128
      bottom_width: 4
      ch: 64
      n_classes: 200


  discriminator:
      fn: dis_models/snresnet_small.py
      name: SNResNetProjectionDiscriminator
      args:
        ch: 64
        n_classes: 200

dataset:
  dataset_fn: datasets/cub.py
  dataset_name: Cub2011Dataset
  args:
    path: datasets/image_list_cub.txt
    size: 128
    resize_method: bilinear
    augmentation: True

adam:
  alpha: 0.0002
  beta1: 0.0
  beta2: 0.9

updater:
  fn: updater.py
  name: Updater
  args:
    n_dis: 5
    n_gen_samples: 32
    conditional: True
    loss_type: hinge
